name: conda_debruijn
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - astroid=2.4.2
  - attrs=20.2.0
  - ca-certificates=2020.10.14
  - certifi=2020.6.20
  - coverage=5.3
  - decorator=4.4.2
  - iniconfig=1.0.1
  - isort=5.6.4
  - lazy-object-proxy=1.4.3
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20191231
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libstdcxx-ng=9.1.0
  - mccabe=0.6.1
  - more-itertools=8.5.0
  - ncurses=6.2
  - networkx=2.5
  - openssl=1.1.1h
  - packaging=20.4
  - pip=20.2.3
  - pluggy=0.13.1
  - py=1.9.0
  - pylint=2.6.0
  - pyparsing=2.4.7
  - pytest=6.1.1
  - pytest-cov=2.10.1
  - python=3.8.5
  - readline=8.0
  - setuptools=50.3.0
  - six=1.15.0
  - sqlite=3.33.0
  - tk=8.6.10
  - toml=0.10.1
  - wheel=0.35.1
  - wrapt=1.11.2
  - xz=5.2.5
  - zlib=1.2.11
