name: conda_debruijn
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - astroid=2.4.2
  - attrs=20.2.0
  - blas=1.0
  - ca-certificates=2020.10.14
  - certifi=2020.6.20
  - coverage=5.3
  - cycler=0.10.0
  - dbus=1.13.18
  - decorator=4.4.2
  - expat=2.2.10
  - fontconfig=2.13.0
  - freetype=2.10.3
  - glib=2.66.1
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - iniconfig=1.0.1
  - intel-openmp=2020.2
  - isort=5.6.4
  - jpeg=9b
  - kiwisolver=1.2.0
  - lazy-object-proxy=1.4.3
  - lcms2=2.11
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20191231
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libpng=1.6.37
  - libstdcxx-ng=9.1.0
  - libtiff=4.1.0
  - libuuid=1.0.3
  - libxcb=1.14
  - libxml2=2.9.10
  - lz4-c=1.9.2
  - matplotlib=3.3.1
  - matplotlib-base=3.3.1
  - mccabe=0.6.1
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.2.0
  - mkl_random=1.1.1
  - more-itertools=8.5.0
  - ncurses=6.2
  - networkx=2.5
  - numpy=1.19.1
  - numpy-base=1.19.1
  - olefile=0.46
  - openssl=1.1.1h
  - packaging=20.4
  - pcre=8.44
  - pillow=8.0.0
  - pip=20.2.3
  - pluggy=0.13.1
  - py=1.9.0
  - pylint=2.6.0
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pytest=6.1.1
  - pytest-cov=2.10.1
  - python=3.8.5
  - python-dateutil=2.8.1
  - qt=5.9.7
  - readline=8.0
  - setuptools=50.3.0
  - sip=4.19.13
  - six=1.15.0
  - sqlite=3.33.0
  - tk=8.6.10
  - toml=0.10.1
  - tornado=6.0.4
  - wheel=0.35.1
  - wrapt=1.11.2
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.5
